name: Deploy Workflow
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build docker images for Forest Portfolio
              run: |
                  docker build -t forest-portfolio:latest .

            - name: Build and push Forest image
              run: |
                  docker build -t sahanlahiru/sahan:forest .
                  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                  docker push sahanlahiru/sahan:forest
                  docker logout
                  echo "Docker image pushed successfully"
            - name: Notify the deployhub - Add an issue in public repo using the current action token
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/sahanweerasiri/deployhub/issues \
                    -d '{"title":"New deployment for Forest Portfolio","body":"A new deployment has been triggered for the Forest Portfolio. Please check the latest changes and ensure everything is running smoothly."}'
